---

- name: install  packages and utils
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 5400
    allow_unauthenticated: yes
  with_items:
   - ubuntu-desktop


- name: update sshd config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication.*no'
    line: 'PasswordAuthentication=yes'
  notify:
    - restart sshd
